manifest:
  self:
    path: zephyr-cmock-unity-module

  remotes:
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch

  projects:
    - name: cmock
      path: test/cmock
      remote: throwtheswitch
      revision: v2.5.3
    - name: unity
      path: test/cmock/vendor/unity
      remote: throwtheswitch
      revision: v2.5.2
