manifest:
  self:
    path: zephyr-cmock-unity-module

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch

  projects:
    - name: zephyr
      path: zephyr
      remote: zephyrproject-rtos
      revision: v3.2.0
      import: true
    - name: cmock
      path: test/cmock
      remote: throwtheswitch
      revision: v2.5.3
    - name: unity
      path: test/cmock/vendor/unity
      remote: throwtheswitch
      revision: v2.5.2
